# Generated by Django 3.1.1 on 2020-09-26 20:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='current_price',
            field=models.DecimalField(decimal_places=2, max_digits=11, null=True),
        ),
    ]
